"""
Which GICS-style sector each stock in universe.py belongs to. Used only for
the sector diversification cap (see settings.MAX_STOCKS_PER_SECTOR) — nothing
else reads this. Broad-market ETFs (SPY/QQQ/DIA/IWM) are tagged "ETF" and
don't count against any sector's cap.

Approximate on purpose — a stock that straddles two sectors is filed under
its dominant business. Good enough for "don't accidentally hold 6 tech
names and call it diversified"; not meant to be authoritative GICS data.
"""

SECTOR = {
    "A": "Health Care", "AAL": "Industrials", "AAPL": "Information Technology",
    "ABBV": "Health Care", "ABNB": "Consumer Discretionary", "ABT": "Health Care",
    "ACN": "Information Technology", "ADBE": "Information Technology", "ADI": "Information Technology",
    "ADM": "Consumer Staples", "ADP": "Industrials", "ADSK": "Information Technology",
    "AEP": "Utilities", "AJG": "Financials", "AKAM": "Information Technology",
    "ALB": "Materials", "ALL": "Financials", "AMAT": "Information Technology",
    "AMD": "Information Technology", "AME": "Industrials", "AMGN": "Health Care",
    "AMT": "Real Estate", "AMZN": "Consumer Discretionary", "AON": "Financials",
    "APH": "Information Technology", "APO": "Financials", "ARES": "Financials",
    "ARM": "Information Technology", "AVGO": "Information Technology", "AXON": "Industrials",
    "AXP": "Financials", "AZO": "Consumer Discretionary", "BA": "Industrials",
    "BAC": "Financials", "BBY": "Consumer Discretionary", "BDX": "Health Care",
    "BKNG": "Consumer Discretionary", "BKR": "Energy", "BLK": "Financials",
    "BMY": "Health Care", "BRK.B": "Financials", "BSX": "Health Care", "BX": "Financials",
    "C": "Financials", "CAH": "Health Care", "CARR": "Industrials", "CAT": "Industrials",
    "CB": "Financials", "CCL": "Consumer Discretionary", "CDNS": "Information Technology",
    "CDW": "Information Technology", "CEG": "Utilities", "CF": "Materials",
    "CHTR": "Communication Services", "CI": "Health Care", "CL": "Consumer Staples",
    "CMCSA": "Communication Services", "CME": "Financials", "CMG": "Consumer Discretionary",
    "CMI": "Industrials", "COF": "Financials", "COIN": "Financials", "COP": "Energy",
    "COR": "Health Care", "COST": "Consumer Staples", "CRM": "Information Technology",
    "CRWD": "Information Technology", "CSCO": "Information Technology", "CSX": "Industrials",
    "CTAS": "Industrials", "CTSH": "Information Technology", "CTVA": "Materials",
    "CVS": "Health Care", "CVX": "Energy", "DAL": "Industrials", "DASH": "Consumer Discretionary",
    "DDOG": "Information Technology", "DE": "Industrials", "DELL": "Information Technology",
    "DHR": "Health Care", "DIA": "ETF", "DIS": "Communication Services",
    "DKNG": "Consumer Discretionary", "DLR": "Real Estate", "DLTR": "Consumer Discretionary",
    "DUK": "Utilities", "DVN": "Energy", "DXCM": "Health Care", "EBAY": "Consumer Discretionary",
    "ECL": "Materials", "EL": "Consumer Staples", "ELV": "Health Care", "EME": "Industrials",
    "EMR": "Industrials", "EOG": "Energy", "EQIX": "Real Estate", "EQT": "Energy",
    "ETN": "Industrials", "EXPE": "Consumer Discretionary", "F": "Consumer Discretionary",
    "FANG": "Energy", "FAST": "Industrials", "FCX": "Materials", "FDX": "Industrials",
    "FITB": "Financials", "FLEX": "Information Technology", "FOXA": "Communication Services",
    "FSLR": "Information Technology", "FTNT": "Information Technology", "GD": "Industrials",
    "GE": "Industrials", "GILD": "Health Care", "GIS": "Consumer Staples",
    "GLW": "Information Technology", "GM": "Consumer Discretionary",
    "GOOG": "Communication Services", "GOOGL": "Communication Services", "GPN": "Financials",
    "GS": "Financials", "GWW": "Industrials", "HAL": "Energy", "HBAN": "Financials",
    "HCA": "Health Care", "HD": "Consumer Discretionary", "HLT": "Consumer Discretionary",
    "HON": "Industrials", "HOOD": "Financials", "HPE": "Information Technology",
    "HPQ": "Information Technology", "HUBS": "Information Technology", "HUM": "Health Care",
    "HWM": "Industrials", "IBM": "Information Technology", "ICE": "Financials",
    "IDXX": "Health Care", "ILMN": "Health Care", "INTC": "Information Technology",
    "INTU": "Information Technology", "IQV": "Health Care", "IR": "Industrials",
    "ISRG": "Health Care", "IT": "Information Technology", "IWM": "ETF",
    "JBL": "Information Technology", "JCI": "Industrials", "JNJ": "Health Care",
    "JPM": "Financials", "KDP": "Consumer Staples", "KEYS": "Information Technology",
    "KHC": "Consumer Staples", "KKR": "Financials", "KLAC": "Information Technology",
    "KMB": "Consumer Staples", "KMI": "Energy", "KO": "Consumer Staples", "KR": "Consumer Staples",
    "KVUE": "Consumer Staples", "LHX": "Industrials", "LIN": "Materials", "LLY": "Health Care",
    "LMT": "Industrials", "LNG": "Energy", "LOW": "Consumer Discretionary",
    "LRCX": "Information Technology", "LULU": "Consumer Discretionary",
    "LYV": "Communication Services", "MA": "Financials", "MAR": "Consumer Discretionary",
    "MCD": "Consumer Discretionary", "MCHP": "Information Technology", "MCK": "Health Care",
    "MCO": "Financials", "MDB": "Information Technology", "MDLZ": "Consumer Staples",
    "MDT": "Health Care", "MET": "Financials", "META": "Communication Services",
    "MLM": "Materials", "MNST": "Consumer Staples", "MO": "Consumer Staples", "MPC": "Energy",
    "MPWR": "Information Technology", "MRK": "Health Care", "MRNA": "Health Care",
    "MRVL": "Information Technology", "MS": "Financials", "MSCI": "Financials",
    "MSFT": "Information Technology", "MSI": "Information Technology", "MU": "Information Technology",
    "NEE": "Utilities", "NEM": "Materials", "NET": "Information Technology",
    "NFLX": "Communication Services", "NKE": "Consumer Discretionary", "NOC": "Industrials",
    "NOW": "Information Technology", "NRG": "Utilities", "NSC": "Industrials",
    "NUE": "Materials", "NVDA": "Information Technology", "NXPI": "Information Technology",
    "O": "Real Estate", "ODFL": "Industrials", "OKE": "Energy", "ON": "Information Technology",
    "ORCL": "Information Technology", "ORLY": "Consumer Discretionary", "OXY": "Energy",
    "PANW": "Information Technology", "PCAR": "Industrials", "PEP": "Consumer Staples",
    "PFE": "Health Care", "PG": "Consumer Staples", "PGR": "Financials", "PH": "Industrials",
    "PLD": "Real Estate", "PLTR": "Information Technology", "PM": "Consumer Staples",
    "PNC": "Financials", "PPL": "Utilities", "PSX": "Energy", "PWR": "Industrials",
    "PYPL": "Financials", "QCOM": "Information Technology", "QQQ": "ETF",
    "RBLX": "Communication Services", "RCL": "Consumer Discretionary", "REGN": "Health Care",
    "RIVN": "Consumer Discretionary", "RMD": "Health Care", "ROK": "Industrials",
    "ROP": "Industrials", "ROST": "Consumer Discretionary", "RSG": "Industrials",
    "RTX": "Industrials", "SBUX": "Consumer Discretionary", "SCHW": "Financials",
    "SHW": "Materials", "SLB": "Energy", "SMCI": "Information Technology",
    "SNOW": "Information Technology", "SNPS": "Information Technology", "SO": "Utilities",
    "SPGI": "Financials", "SPOT": "Communication Services", "SPY": "ETF", "SRE": "Utilities",
    "STLD": "Materials", "STX": "Information Technology", "SWKS": "Information Technology",
    "SYK": "Health Care", "T": "Communication Services", "TDG": "Industrials",
    "TEAM": "Information Technology", "TEL": "Information Technology", "TER": "Information Technology",
    "TFC": "Financials", "TGT": "Consumer Discretionary", "TJX": "Consumer Discretionary",
    "TMO": "Health Care", "TMUS": "Communication Services", "TPR": "Consumer Discretionary",
    "TRGP": "Energy", "TRV": "Financials", "TSCO": "Consumer Discretionary",
    "TSLA": "Consumer Discretionary", "TT": "Industrials", "TTD": "Communication Services",
    "TTWO": "Communication Services", "TXN": "Information Technology", "UAL": "Industrials",
    "UBER": "Industrials", "ULTA": "Consumer Discretionary", "UNH": "Health Care",
    "UNP": "Industrials", "UPS": "Industrials", "URI": "Industrials", "USB": "Financials",
    "V": "Financials", "VLO": "Energy", "VRTX": "Health Care", "VST": "Utilities",
    "VZ": "Communication Services", "W": "Consumer Discretionary", "WAT": "Health Care",
    "WBD": "Communication Services", "WDAY": "Information Technology",
    "WDC": "Information Technology", "WELL": "Real Estate", "WFC": "Financials",
    "WM": "Industrials", "WMB": "Energy", "WMT": "Consumer Staples", "XEL": "Utilities",
    "XOM": "Energy", "YUM": "Consumer Discretionary", "ZBRA": "Information Technology",
    "ZS": "Information Technology", "ZTS": "Health Care",
}


def sector_of(symbol):
    from universe_big import BIG_SECTOR   # sectors for the ~1700 extra names (from Nasdaq's screener)
    s = symbol.upper()
    return SECTOR.get(s) or BIG_SECTOR.get(s, "Other")
