"""
BIG_UNIVERSE: ~2000 most-traded US stocks for the main account.
Built by _build_big_universe.py on 2026-09-28 (hand-picked 300 from universe.py + the most-traded others,
smallest added name trades ~$18M/day). Re-run that script to refresh.

BIG_SECTOR: sector for each name NOT already in sectors.SECTOR (from Nasdaq's screener).
"""

BIG_UNIVERSE = [
    "A", "AA", "AAL", "AAMI", "AAOI", "AAON", "AAP", "AAPL", "ABBV", "ABCB", "ABCL", "ABG",
    "ABM", "ABNB", "ABSI", "ABT", "ABVX", "ACA", "ACAD", "ACGL", "ACHC", "ACHR", "ACI", "ACIW",
    "ACLS", "ACM", "ACMR", "ACN", "ACVA", "ADBE", "ADC", "ADEA", "ADI", "ADM", "ADMA", "ADP",
    "ADPT", "ADSK", "ADT", "ADUS", "AEE", "AEG", "AEHR", "AEIS", "AEM", "AEO", "AEP", "AER",
    "AES", "AESI", "AEVA", "AFG", "AFL", "AFRM", "AG", "AGCO", "AGI", "AGIO", "AGL", "AGM",
    "AGNC", "AGO", "AGX", "AGYS", "AHR", "AI", "AIG", "AIR", "AIT", "AIZ", "AJG", "AKAM",
    "AKR", "ALAB", "ALB", "ALC", "ALG", "ALGM", "ALGN", "ALGT", "ALH", "ALHC", "ALK", "ALKS",
    "ALKT", "ALL", "ALLE", "ALLY", "ALM", "ALMS", "ALNT", "ALNY", "ALOY", "ALRM", "ALSN", "ALV",
    "AM", "AMAT", "AMBA", "AMBQ", "AMCR", "AMD", "AME", "AMG", "AMGN", "AMH", "AMKR", "AMLX",
    "AMN", "AMP", "AMPL", "AMPX", "AMR", "AMRX", "AMRZ", "AMSC", "AMT", "AMTM", "AMZN", "AN",
    "ANAB", "ANDE", "ANDG", "ANET", "ANF", "ANIP", "AON", "AOS", "APA", "APAM", "APD", "APG",
    "APH", "APLD", "APLE", "APO", "APP", "APPF", "APPN", "APPS", "APTV", "AQN", "AR", "ARCB",
    "ARCC", "ARE", "ARES", "ARGX", "ARI", "ARM", "ARMK", "AROC", "ARQT", "ARR", "ARW", "ARWR",
    "ARX", "AS", "ASAN", "ASB", "ASH", "ASM", "ASML", "ASND", "ASO", "ASST", "ASTS", "ASX",
    "ATAT", "ATEN", "ATEX", "ATI", "ATKR", "ATMU", "ATO", "ATR", "ATRC", "ATRO", "AU", "AUB",
    "AUGO", "AUR", "AVA", "AVAH", "AVAV", "AVGO", "AVNT", "AVPT", "AVT", "AVTR", "AVY", "AWI",
    "AWK", "AWR", "AX", "AXGN", "AXON", "AXP", "AXS", "AXSM", "AXTA", "AXTI", "AYI", "AZN",
    "AZO", "AZTA", "AZZ", "B", "BA", "BABA", "BAC", "BAH", "BALL", "BAM", "BANC", "BAND",
    "BANR", "BAP", "BATRK", "BAX", "BB", "BBIO", "BBNX", "BBT", "BBVA", "BBWI", "BBY", "BC",
    "BCC", "BCE", "BCO", "BCPC", "BCRX", "BCS", "BDC", "BDX", "BE", "BEAM", "BEKE", "BEN",
    "BEPC", "BETA", "BFAM", "BFH", "BFLY", "BG", "BGC", "BH", "BHE", "BHF", "BHP", "BHVN",
    "BIDU", "BIIB", "BILI", "BILL", "BIO", "BIPC", "BIRK", "BJ", "BJRI", "BKD", "BKE", "BKH",
    "BKNG", "BKR", "BKSY", "BKU", "BKV", "BL", "BLBD", "BLDR", "BLFS", "BLK", "BLKB", "BLLN",
    "BLSH", "BLTE", "BLZE", "BMA", "BMI", "BMNR", "BMO", "BMRN", "BMY", "BN", "BNL", "BNS",
    "BNTX", "BNY", "BOH", "BOKF", "BOOT", "BOX", "BP", "BPOP", "BR", "BRBR", "BRK.B", "BRKR",
    "BRO", "BROS", "BRSL", "BRUN", "BRX", "BRZE", "BSX", "BSY", "BTDR", "BTG", "BTI", "BTSG",
    "BTU", "BUD", "BULL", "BURL", "BUSE", "BVN", "BW", "BWA", "BWIN", "BWXT", "BX", "BXMT",
    "BXP", "BXSL", "BYD", "BZ", "C", "CACC", "CACI", "CAG", "CAH", "CAI", "CAKE", "CALM",
    "CALX", "CALY", "CAMT", "CAPR", "CAR", "CARG", "CARR", "CART", "CASY", "CAT", "CATY", "CAVA",
    "CB", "CBC", "CBOE", "CBRE", "CBRL", "CBSH", "CBT", "CBZ", "CC", "CCC", "CCEP", "CCI",
    "CCJ", "CCK", "CCL", "CCXI", "CDE", "CDNA", "CDNL", "CDNS", "CDP", "CDW", "CE", "CECO",
    "CEG", "CELC", "CELH", "CENX", "CERT", "CEVA", "CF", "CFG", "CFR", "CG", "CGAU", "CGNX",
    "CGON", "CHD", "CHDN", "CHE", "CHEF", "CHH", "CHKP", "CHRD", "CHRW", "CHTR", "CHWY", "CHYM",
    "CI", "CIEN", "CIFR", "CIGI", "CINF", "CL", "CLBK", "CLBT", "CLDX", "CLF", "CLH", "CLMT",
    "CLS", "CLSK", "CLX", "CLYM", "CM", "CMC", "CMCSA", "CME", "CMG", "CMI", "CMPS", "CMS",
    "CNA", "CNC", "CNH", "CNI", "CNK", "CNM", "CNMD", "CNO", "CNP", "CNQ", "CNR", "CNS",
    "CNX", "CNXC", "COCO", "COF", "COGT", "COHR", "COHU", "COIN", "COKE", "COLB", "COLD", "COLL",
    "COLM", "COMP", "CON", "COO", "COP", "COR", "CORT", "CORZ", "COST", "CP", "CPA", "CPAY",
    "CPB", "CPK", "CPNG", "CPRI", "CPRT", "CPT", "CR", "CRAI", "CRBG", "CRC", "CRCL", "CRDO",
    "CRGY", "CRH", "CRI", "CRK", "CRL", "CRM", "CRML", "CROX", "CRS", "CRSP", "CRUS", "CRWD",
    "CRWV", "CSCO", "CSGP", "CSIQ", "CSL", "CSTM", "CSW", "CSX", "CTAS", "CTRE", "CTRI", "CTSH",
    "CTVA", "CUBE", "CUBI", "CURB", "CUZ", "CVBF", "CVCO", "CVE", "CVI", "CVLT", "CVNA", "CVS",
    "CVSA", "CVX", "CW", "CWEN", "CWK", "CWST", "CWT", "CX", "CXT", "CXW", "CYTK", "CZR",
    "D", "DAL", "DAN", "DAR", "DASH", "DAVE", "DB", "DBRG", "DBX", "DCI", "DCO", "DD",
    "DDOG", "DDS", "DE", "DECK", "DEI", "DELL", "DEO", "DFTX", "DG", "DGII", "DGX", "DHI",
    "DHR", "DHT", "DIA", "DINO", "DIOD", "DIS", "DJCO", "DJT", "DK", "DKNG", "DKS", "DLB",
    "DLO", "DLR", "DLTR", "DNLI", "DNOW", "DNTH", "DOC", "DOCN", "DOCS", "DOCU", "DORM", "DOV",
    "DOW", "DOX", "DPZ", "DRH", "DRI", "DRS", "DSGX", "DT", "DTE", "DTM", "DUK", "DUOL",
    "DV", "DVA", "DVN", "DX", "DXC", "DXCM", "DXPE", "DY", "DYN", "EAT", "EBAY", "EBC",
    "EC", "ECG", "ECHO", "ECL", "ECO", "ECPG", "ED", "EDU", "EEFT", "EFOR", "EFX", "EG",
    "EGO", "EGP", "EHC", "EIX", "EL", "ELAN", "ELF", "ELS", "ELV", "ELVN", "EMBJ", "EME",
    "EMN", "EMR", "ENB", "ENOV", "ENPH", "ENR", "ENS", "ENSG", "ENTG", "ENVA", "EOG", "EPAM",
    "EPD", "EPR", "EPRT", "EQH", "EQIX", "EQNR", "EQPT", "EQT", "EQX", "ERAS", "ERIC", "ERIE",
    "ERO", "ES", "ESAB", "ESE", "ESI", "ESLT", "ESNT", "ESQ", "ESS", "ESTA", "ESTC", "ETN",
    "ETON", "ETOR", "ETR", "ETSY", "EVR", "EVRG", "EW", "EWBC", "EWTX", "EXC", "EXE", "EXEL",
    "EXK", "EXLS", "EXP", "EXPD", "EXPE", "EXPO", "EXR", "EXTR", "EYE", "EZPW", "F", "FA",
    "FAF", "FANG", "FAST", "FBIN", "FBK", "FBP", "FCEL", "FCF", "FCFS", "FCN", "FCNCA", "FCPT",
    "FCX", "FDS", "FDX", "FE", "FEIM", "FELE", "FER", "FERG", "FFBC", "FFIN", "FFIV", "FHB",
    "FHI", "FHN", "FIBK", "FICO", "FIG", "FIGR", "FIGS", "FIS", "FISV", "FITB", "FIVE", "FIVN",
    "FIX", "FLEX", "FLG", "FLNC", "FLO", "FLR", "FLS", "FLUT", "FLY", "FLYW", "FMC", "FMX",
    "FN", "FNB", "FND", "FNF", "FNV", "FORM", "FOUR", "FOX", "FOXA", "FPS", "FR", "FRO",
    "FROG", "FRPT", "FRSH", "FRT", "FSK", "FSLR", "FSLY", "FSM", "FSS", "FSV", "FTAI", "FTDR",
    "FTI", "FTNT", "FTRE", "FTS", "FTV", "FUL", "FULT", "FUN", "FUTU", "FWONK", "G", "GAP",
    "GATX", "GBCI", "GCT", "GD", "GDDY", "GDS", "GE", "GEHC", "GEN", "GENI", "GEO", "GEV",
    "GFF", "GFI", "GFL", "GFS", "GGAL", "GGG", "GH", "GHC", "GHM", "GIB", "GIL", "GILD",
    "GIS", "GKOS", "GL", "GLBE", "GLNG", "GLOB", "GLPI", "GLW", "GLXY", "GM", "GMAB", "GME",
    "GMED", "GNL", "GNRC", "GNTX", "GNW", "GO", "GOF", "GOLD", "GOLF", "GOOG", "GOOGL", "GPC",
    "GPCR", "GPGI", "GPI", "GPK", "GPN", "GPOR", "GPRE", "GRAL", "GRMN", "GRND", "GRPN", "GS",
    "GSAT", "GSHD", "GSK", "GT", "GTES", "GTLB", "GTX", "GVA", "GWRE", "GWW", "GXO", "H",
    "HAE", "HAL", "HALO", "HAPN", "HAS", "HASI", "HAYW", "HBAN", "HBM", "HCA", "HCC", "HCI",
    "HD", "HDB", "HE", "HEI", "HESM", "HGV", "HHH", "HIG", "HII", "HIMS", "HIW", "HL",
    "HLI", "HLIO", "HLN", "HLNE", "HLT", "HMC", "HMY", "HNGE", "HNI", "HOG", "HOMB", "HON",
    "HOOD", "HP", "HPE", "HPQ", "HQY", "HR", "HRB", "HRI", "HRL", "HRMY", "HROW", "HSAI",
    "HSBC", "HSIC", "HST", "HSY", "HTFL", "HTGC", "HTHT", "HTO", "HUBB", "HUBG", "HUBS", "HUM",
    "HUN", "HURN", "HUT", "HWC", "HWKN", "HWM", "HXL", "HYMC", "HZO", "IAG", "IBKR", "IBM",
    "IBN", "IBOC", "IBP", "IBRX", "ICE", "ICHR", "ICLR", "ICUI", "IDA", "IDCC", "IDXX", "IDYA",
    "IE", "IESC", "IEX", "IFF", "IHG", "IIPR", "ILMN", "IMAX", "IMNM", "IMO", "IMVT", "INBX",
    "INCY", "INDB", "INDV", "INFQ", "INFY", "ING", "INGM", "INGR", "INOD", "INSM", "INSP", "INSW",
    "INTA", "INTC", "INTR", "INTU", "INVH", "IONQ", "IONS", "IOT", "IOVA", "IP", "IPAR", "IPGP",
    "IQV", "IR", "IRDM", "IREN", "IRM", "IRON", "IRT", "IRTC", "ISRG", "IT", "ITGR", "ITRI",
    "ITT", "ITW", "IVR", "IVT", "IVZ", "IWM", "J", "JAZZ", "JBHT", "JBL", "JBS", "JBTM",
    "JCI", "JD", "JEF", "JHX", "JKHY", "JLL", "JNJ", "JOBY", "JOYY", "JPM", "JXN", "KAI",
    "KALU", "KB", "KBH", "KBR", "KD", "KDP", "KEX", "KEY", "KEYS", "KFY", "KGC", "KGS",
    "KHC", "KIM", "KKR", "KLAC", "KLAR", "KLIC", "KMB", "KMI", "KMPR", "KMT", "KMX", "KN",
    "KNF", "KNSA", "KNSL", "KNTK", "KNX", "KO", "KOD", "KR", "KRC", "KRG", "KRMN", "KRYS",
    "KSS", "KT", "KTB", "KTOS", "KURA", "KVUE", "KVYO", "KWR", "KYMR", "L", "LAD", "LAMR",
    "LASR", "LAUR", "LAZ", "LB", "LBRT", "LBTYA", "LCII", "LDOS", "LEA", "LECO", "LEGN", "LEN",
    "LEU", "LEVI", "LFST", "LFUS", "LGN", "LGND", "LH", "LHX", "LI", "LIF", "LIFE", "LII",
    "LIN", "LINC", "LIND", "LINE", "LION", "LITE", "LIVN", "LKQ", "LLY", "LLYVK", "LMAT", "LMND",
    "LMT", "LNC", "LNG", "LNT", "LNTH", "LOAR", "LOGI", "LOPE", "LOW", "LPG", "LPLA", "LPTH",
    "LPX", "LQDA", "LRCX", "LRN", "LSCC", "LSTR", "LTC", "LTH", "LTM", "LULU", "LUMN", "LUNR",
    "LUV", "LVS", "LW", "LXP", "LYB", "LYFT", "LYG", "LYV", "LZB", "M", "MA", "MAA",
    "MAC", "MAIN", "MAN", "MANE", "MANH", "MAR", "MARA", "MAS", "MAT", "MATX", "MBLY", "MBX",
    "MC", "MCD", "MCHP", "MCK", "MCO", "MCY", "MD", "MDB", "MDGL", "MDLN", "MDLZ", "MDT",
    "MDU", "MEDP", "MELI", "MEOH", "MET", "META", "METC", "MFC", "MFG", "MGA", "MGM", "MGNI",
    "MGY", "MHK", "MHO", "MIAX", "MIDD", "MIR", "MIRM", "MKC", "MKL", "MKSI", "MKTX", "MLI",
    "MLM", "MLTX", "MLYS", "MMED", "MMM", "MMS", "MMSI", "MMYT", "MNDY", "MNPR", "MNST", "MO",
    "MOD", "MOH", "MORN", "MOS", "MP", "MPC", "MPWR", "MRCY", "MRK", "MRNA", "MRP", "MRSH",
    "MRVL", "MRX", "MS", "MSA", "MSCI", "MSFT", "MSGE", "MSGS", "MSI", "MSM", "MSTR", "MT",
    "MTB", "MTCH", "MTD", "MTDR", "MTG", "MTH", "MTN", "MTRN", "MTSI", "MTZ", "MU", "MUFG",
    "MUR", "MUSA", "MWA", "MWH", "MXL", "MYRG", "MZTI", "NAMS", "NAT", "NATL", "NAVN", "NBIS",
    "NBIX", "NBR", "NCLH", "NCNO", "NDAQ", "NDSN", "NE", "NEE", "NEM", "NEO", "NEOG", "NESR",
    "NET", "NEU", "NFG", "NFLX", "NG", "NGG", "NHC", "NHI", "NI", "NIC", "NICE", "NIQ",
    "NJR", "NKE", "NKTR", "NLY", "NMIH", "NMRK", "NN", "NNE", "NNN", "NOC", "NOG", "NOK",
    "NOV", "NOVT", "NOW", "NPO", "NRG", "NRIX", "NSC", "NSIT", "NSP", "NTAP", "NTCT", "NTES",
    "NTLA", "NTNX", "NTR", "NTRA", "NTRS", "NTSK", "NTST", "NU", "NUAI", "NUE", "NUTX", "NUVB",
    "NVAX", "NVCR", "NVDA", "NVMI", "NVO", "NVR", "NVS", "NVST", "NVT", "NVTS", "NWE", "NWG",
    "NWL", "NWS", "NWSA", "NXE", "NXPI", "NXST", "NXT", "NYT", "O", "OBDC", "OC", "OCUL",
    "ODFL", "OGE", "OGN", "OGS", "OHI", "OI", "OII", "OKE", "OKLO", "OKTA", "OLED", "OLLI",
    "OLN", "OMC", "OMCL", "OMDA", "OMER", "OMF", "ON", "ONB", "ONC", "ONDS", "ONON", "ONTO",
    "OPCH", "OPLN", "OR", "ORA", "ORC", "ORCL", "ORI", "ORKA", "ORLY", "OSCR", "OSIS", "OSK",
    "OSW", "OTEX", "OTIS", "OTTR", "OUST", "OUT", "OVV", "OWL", "OXY", "OZK", "P", "PAAS",
    "PAC", "PACS", "PAG", "PAGS", "PANW", "PARR", "PATH", "PATK", "PAY", "PAYC", "PAYO", "PAYX",
    "PB", "PBA", "PBF", "PBH", "PBI", "PBR", "PCAR", "PCG", "PCOR", "PCTY", "PCVX", "PDD",
    "PDFS", "PDI", "PEB", "PECO", "PEG", "PEGA", "PEN", "PENG", "PENN", "PEP", "PFE", "PFG",
    "PFGC", "PFS", "PFSI", "PG", "PGEN", "PGNY", "PGR", "PGY", "PH", "PHG", "PHIN", "PHM",
    "PHVS", "PI", "PII", "PINS", "PIPR", "PJT", "PK", "PKG", "PL", "PLAB", "PLD", "PLMR",
    "PLNT", "PLPC", "PLSE", "PLTR", "PLUS", "PLXS", "PM", "PNC", "PNFP", "PNR", "PNW", "PODD",
    "POET", "PONY", "POOL", "POR", "POST", "POWI", "POWL", "PPC", "PPG", "PPL", "PPLI", "PPTA",
    "PR", "PRAX", "PRCH", "PRCT", "PRDO", "PRG", "PRGO", "PRGS", "PRI", "PRIM", "PRKS", "PRM",
    "PRMB", "PRU", "PRVA", "PSA", "PSKY", "PSMT", "PSN", "PSNL", "PSX", "PTC", "PTCT", "PTEN",
    "PTGX", "PTRN", "PUK", "PUMP", "PURR", "PVH", "PVLA", "PWR", "PYPL", "PZZA", "Q", "QBTS",
    "QCOM", "QDEL", "QGEN", "QLYS", "QMCO", "QQQ", "QRVO", "QSR", "QTWO", "QUBT", "QURE", "QXO",
    "R", "RACE", "RAL", "RAMP", "RARE", "RBA", "RBC", "RBLX", "RBRK", "RCAT", "RCI", "RCL",
    "RCUS", "RDDT", "RDN", "RDNT", "RDW", "RDY", "REAL", "REG", "REGN", "RELX", "RELY", "REPL",
    "REXR", "REYN", "REZI", "RF", "RGA", "RGEN", "RGLD", "RGTI", "RH", "RHI", "RHLD", "RHP",
    "RIG", "RIO", "RIOT", "RITM", "RIVN", "RJF", "RKLB", "RKT", "RL", "RLAY", "RLI", "RLJ",
    "RMBS", "RMD", "RNG", "RNR", "RNST", "ROAD", "ROG", "ROIV", "ROK", "ROKU", "ROL", "ROP",
    "ROST", "RPD", "RPM", "RPRX", "RRC", "RRR", "RRX", "RS", "RSG", "RSI", "RTO", "RTX",
    "RUM", "RUN", "RUSHA", "RVLV", "RVMD", "RVTY", "RXO", "RY", "RYAAY", "RYAN", "RYN", "RYTM",
    "S", "SAH", "SAIA", "SAIC", "SAIL", "SAM", "SAN", "SANM", "SAP", "SARO", "SATL", "SBAC",
    "SBCF", "SBET", "SBH", "SBLK", "SBRA", "SBS", "SBSW", "SBUX", "SCCO", "SCHW", "SCI", "SDRL",
    "SE", "SEB", "SEDG", "SEI", "SEIC", "SEZL", "SF", "SFBS", "SFD", "SFM", "SFNC", "SG",
    "SGHC", "SGI", "SGRY", "SHAK", "SHAZ", "SHC", "SHEL", "SHLS", "SHO", "SHOO", "SHOP", "SHW",
    "SIG", "SIGI", "SII", "SIMO", "SIRI", "SITE", "SITM", "SJM", "SKM", "SKT", "SKWD", "SKY",
    "SKYW", "SLAB", "SLB", "SLDE", "SLF", "SLG", "SLGN", "SLM", "SLS", "SM", "SMA", "SMCI",
    "SMFG", "SMG", "SMMT", "SMPL", "SMR", "SMTC", "SN", "SNA", "SNAP", "SNDK", "SNDR", "SNDX",
    "SNEX", "SNN", "SNOW", "SNPS", "SNX", "SNY", "SO", "SOBO", "SOFI", "SOLS", "SOLV", "SON",
    "SONO", "SONY", "SOUN", "SPB", "SPG", "SPGI", "SPHR", "SPOT", "SPSC", "SPXC", "SPY", "SQM",
    "SR", "SRAD", "SRE", "SRPT", "SRRK", "SSB", "SSD", "SSNC", "SSRM", "ST", "STAA", "STAG",
    "STE", "STEP", "STLD", "STM", "STN", "STNE", "STNG", "STOK", "STRA", "STRL", "STT", "STUB",
    "STWD", "STX", "STZ", "SU", "SUI", "SUNB", "SUPN", "SUZ", "SVM", "SW", "SWK", "SWKS",
    "SWX", "SXI", "SXT", "SYF", "SYK", "SYM", "SYNA", "SYRE", "SYY", "T", "TAC", "TAK",
    "TAL", "TALO", "TAP", "TARS", "TBBB", "TBBK", "TCBI", "TCOM", "TD", "TDC", "TDG", "TDOC",
    "TDS", "TDW", "TDY", "TEAM", "TECH", "TECK", "TEL", "TEM", "TENB", "TER", "TEX", "TFC",
    "TFII", "TFX", "TGB", "TGT", "TGTX", "TH", "THC", "THG", "THO", "TIGO", "TJX", "TKO",
    "TKR", "TLN", "TM", "TMDX", "TME", "TMO", "TMUS", "TNDM", "TNET", "TNGX", "TNK", "TNL",
    "TOL", "TOST", "TOWN", "TPB", "TPC", "TPG", "TPL", "TPR", "TREX", "TRGP", "TRI", "TRIP",
    "TRMB", "TRN", "TRNO", "TROW", "TRP", "TRU", "TRV", "TRVI", "TS", "TSCO", "TSEM", "TSLA",
    "TSM", "TSN", "TT", "TTAN", "TTC", "TTD", "TTE", "TTEK", "TTMI", "TTWO", "TU", "TVTX",
    "TW", "TWLO", "TWST", "TX", "TXG", "TXN", "TXNM", "TXRH", "TXT", "TYL", "U", "UAL",
    "UBER", "UBS", "UBSI", "UCB", "UCTT", "UDR", "UEC", "UFPI", "UFPT", "UGI", "UGP", "UHS",
    "UI", "UL", "ULS", "ULTA", "UMAC", "UMBF", "UMC", "UNF", "UNFI", "UNH", "UNIT", "UNM",
    "UNP", "UPS", "UPST", "UPWK", "URBN", "URGN", "URI", "USAR", "USB", "USFD", "UTHR", "UTI",
    "UTZ", "UUUU", "V", "VAC", "VAL", "VALE", "VC", "VCEL", "VCTR", "VCYT", "VECO", "VEEV",
    "VERA", "VERX", "VFC", "VG", "VIAV", "VICI", "VICR", "VIK", "VIPS", "VIRT", "VISN", "VIST",
    "VKTX", "VLO", "VLTO", "VLY", "VMC", "VMI", "VMRK", "VNET", "VNO", "VNOM", "VNT", "VOD",
    "VOR", "VOYA", "VOYG", "VPG", "VRDN", "VRNS", "VRSK", "VRSN", "VRT", "VRTS", "VRTX", "VSAT",
    "VSEC", "VSH", "VSNT", "VST", "VSXY", "VTR", "VTRS", "VVV", "VVX", "VYX", "VZ", "W",
    "WAB", "WAFD", "WAL", "WAT", "WAY", "WBD", "WBI", "WCC", "WCN", "WDAY", "WDC", "WDFC",
    "WEC", "WELL", "WEN", "WERN", "WEX", "WFC", "WFRD", "WGS", "WH", "WHD", "WHR", "WING",
    "WIX", "WK", "WKC", "WLK", "WLY", "WM", "WMB", "WMG", "WMS", "WMT", "WOLF", "WPC",
    "WPM", "WRB", "WRBY", "WSBC", "WSC", "WSFS", "WSM", "WSO", "WST", "WT", "WTFC", "WTM",
    "WTRG", "WTS", "WTTR", "WTW", "WU", "WULF", "WWD", "WY", "WYFI", "WYNN", "XEL", "XENE",
    "XMTR", "XNCR", "XOM", "XP", "XPEV", "XPO", "XRAY", "XYL", "XYZ", "YELP", "YETI", "YMM",
    "YOU", "YPF", "YSS", "YUM", "YUMC", "Z", "ZBH", "ZBIO", "ZBRA", "ZD", "ZETA", "ZG",
    "ZIM", "ZION", "ZLAB", "ZM", "ZS", "ZTO", "ZTS", "ZWS",
]

BIG_SECTOR = {
    "AA": "Industrials",
    "AAMI": "Financials",
    "AAOI": "Information Technology",
    "AAON": "Industrials",
    "AAP": "Consumer Discretionary",
    "ABCB": "Financials",
    "ABCL": "Health Care",
    "ABG": "Consumer Discretionary",
    "ABM": "Consumer Discretionary",
    "ABSI": "Health Care",
    "ABVX": "Health Care",
    "ACA": "Industrials",
    "ACAD": "Health Care",
    "ACGL": "Financials",
    "ACHC": "Health Care",
    "ACHR": "Industrials",
    "ACI": "Consumer Staples",
    "ACIW": "Information Technology",
    "ACLS": "Information Technology",
    "ACM": "Consumer Discretionary",
    "ACMR": "Information Technology",
    "ACVA": "Consumer Discretionary",
    "ADC": "Real Estate",
    "ADEA": "Communication Services",
    "ADMA": "Health Care",
    "ADPT": "Health Care",
    "ADT": "Consumer Discretionary",
    "ADUS": "Health Care",
    "AEE": "Utilities",
    "AEG": "Financials",
    "AEHR": "Industrials",
    "AEIS": "Information Technology",
    "AEM": "Materials",
    "AEO": "Consumer Discretionary",
    "AER": "Consumer Discretionary",
    "AES": "Industrials",
    "AESI": "Industrials",
    "AEVA": "Consumer Discretionary",
    "AFG": "Financials",
    "AFL": "Financials",
    "AFRM": "Financials",
    "AG": "Materials",
    "AGCO": "Industrials",
    "AGI": "Materials",
    "AGIO": "Health Care",
    "AGL": "Health Care",
    "AGM": "Financials",
    "AGNC": "Real Estate",
    "AGO": "Financials",
    "AGX": "Consumer Discretionary",
    "AGYS": "Information Technology",
    "AHR": "Real Estate",
    "AI": "Information Technology",
    "AIG": "Financials",
    "AIR": "Industrials",
    "AIT": "Consumer Discretionary",
    "AIZ": "Financials",
    "AKR": "Real Estate",
    "ALAB": "Information Technology",
    "ALC": "Health Care",
    "ALG": "Industrials",
    "ALGM": "Information Technology",
    "ALGN": "Health Care",
    "ALGT": "Consumer Discretionary",
    "ALH": "Industrials",
    "ALHC": "Health Care",
    "ALK": "Consumer Discretionary",
    "ALKS": "Health Care",
    "ALKT": "Information Technology",
    "ALLE": "Consumer Discretionary",
    "ALLY": "Financials",
    "ALM": "Materials",
    "ALMS": "Health Care",
    "ALNT": "Industrials",
    "ALNY": "Health Care",
    "ALOY": "Materials",
    "ALRM": "Information Technology",
    "ALSN": "Consumer Discretionary",
    "ALV": "Consumer Discretionary",
    "AM": "Utilities",
    "AMBA": "Information Technology",
    "AMBQ": "Information Technology",
    "AMCR": "Consumer Discretionary",
    "AMG": "Financials",
    "AMH": "Real Estate",
    "AMKR": "Information Technology",
    "AMLX": "Health Care",
    "AMN": "Consumer Discretionary",
    "AMP": "Financials",
    "AMPL": "Information Technology",
    "AMPX": "Miscellaneous",
    "AMR": "Energy",
    "AMRX": "Health Care",
    "AMRZ": "Industrials",
    "AMSC": "Consumer Discretionary",
    "AMTM": "Consumer Discretionary",
    "AN": "Consumer Discretionary",
    "ANAB": "Health Care",
    "ANDE": "Industrials",
    "ANDG": "Consumer Discretionary",
    "ANET": "Communication Services",
    "ANF": "Consumer Discretionary",
    "ANIP": "Health Care",
    "AOS": "Consumer Discretionary",
    "APA": "Energy",
    "APAM": "Financials",
    "APD": "Materials",
    "APG": "Consumer Discretionary",
    "APLD": "Information Technology",
    "APLE": "Real Estate",
    "APP": "Information Technology",
    "APPF": "Information Technology",
    "APPN": "Information Technology",
    "APPS": "Miscellaneous",
    "APTV": "Consumer Discretionary",
    "AQN": "Utilities",
    "AR": "Energy",
    "ARCB": "Industrials",
    "ARCC": "Financials",
    "ARE": "Real Estate",
    "ARGX": "Health Care",
    "ARI": "Real Estate",
    "ARMK": "Consumer Discretionary",
    "AROC": "Utilities",
    "ARQT": "Health Care",
    "ARR": "Real Estate",
    "ARW": "Information Technology",
    "ARWR": "Health Care",
    "ARX": "Financials",
    "AS": "Consumer Discretionary",
    "ASAN": "Information Technology",
    "ASB": "Financials",
    "ASH": "Consumer Discretionary",
    "ASM": "Materials",
    "ASML": "Information Technology",
    "ASND": "Health Care",
    "ASO": "Consumer Discretionary",
    "ASST": "Financials",
    "ASTS": "Consumer Discretionary",
    "ASX": "Information Technology",
    "ATAT": "Consumer Discretionary",
    "ATEN": "Communication Services",
    "ATEX": "Communication Services",
    "ATI": "Industrials",
    "ATKR": "Miscellaneous",
    "ATMU": "Consumer Discretionary",
    "ATO": "Utilities",
    "ATR": "Industrials",
    "ATRC": "Health Care",
    "ATRO": "Industrials",
    "AU": "Materials",
    "AUB": "Financials",
    "AUGO": "Materials",
    "AUR": "Information Technology",
    "AVA": "Utilities",
    "AVAH": "Health Care",
    "AVAV": "Industrials",
    "AVNT": "Industrials",
    "AVPT": "Information Technology",
    "AVT": "Information Technology",
    "AVTR": "Industrials",
    "AVY": "Consumer Discretionary",
    "AWI": "Industrials",
    "AWK": "Utilities",
    "AWR": "Utilities",
    "AX": "Financials",
    "AXGN": "Health Care",
    "AXS": "Financials",
    "AXSM": "Health Care",
    "AXTA": "Consumer Discretionary",
    "AXTI": "Information Technology",
    "AYI": "Consumer Discretionary",
    "AZN": "Health Care",
    "AZTA": "Information Technology",
    "AZZ": "Industrials",
    "B": "Materials",
    "BABA": "Consumer Discretionary",
    "BAH": "Consumer Discretionary",
    "BALL": "Industrials",
    "BAM": "Real Estate",
    "BANC": "Financials",
    "BAND": "Information Technology",
    "BANR": "Financials",
    "BAP": "Financials",
    "BATRK": "Consumer Discretionary",
    "BAX": "Health Care",
    "BB": "Information Technology",
    "BBIO": "Health Care",
    "BBNX": "Health Care",
    "BBT": "Financials",
    "BBVA": "Financials",
    "BBWI": "Consumer Discretionary",
    "BC": "Industrials",
    "BCC": "Consumer Discretionary",
    "BCE": "Communication Services",
    "BCO": "Industrials",
    "BCPC": "Industrials",
    "BCRX": "Health Care",
    "BCS": "Financials",
    "BDC": "Industrials",
    "BE": "Energy",
    "BEAM": "Health Care",
    "BEKE": "Financials",
    "BEN": "Financials",
    "BEPC": "Utilities",
    "BETA": "Industrials",
    "BFAM": "Consumer Discretionary",
    "BFH": "Consumer Discretionary",
    "BFLY": "Health Care",
    "BG": "Consumer Staples",
    "BGC": "Financials",
    "BH": "Consumer Discretionary",
    "BHE": "Information Technology",
    "BHF": "Financials",
    "BHP": "Energy",
    "BHVN": "Health Care",
    "BIDU": "Information Technology",
    "BIIB": "Health Care",
    "BILI": "Information Technology",
    "BILL": "Information Technology",
    "BIO": "Industrials",
    "BIPC": "Consumer Discretionary",
    "BIRK": "Consumer Discretionary",
    "BJ": "Consumer Discretionary",
    "BJRI": "Consumer Discretionary",
    "BKD": "Health Care",
    "BKE": "Consumer Discretionary",
    "BKH": "Utilities",
    "BKSY": "Information Technology",
    "BKU": "Financials",
    "BKV": "Energy",
    "BL": "Information Technology",
    "BLBD": "Consumer Discretionary",
    "BLDR": "Consumer Discretionary",
    "BLFS": "Health Care",
    "BLKB": "Information Technology",
    "BLLN": "Health Care",
    "BLSH": "Financials",
    "BLTE": "Health Care",
    "BLZE": "Information Technology",
    "BMA": "Financials",
    "BMI": "Industrials",
    "BMNR": "Financials",
    "BMO": "Financials",
    "BMRN": "Health Care",
    "BN": "Real Estate",
    "BNL": "Real Estate",
    "BNS": "Financials",
    "BNTX": "Health Care",
    "BNY": "Financials",
    "BOH": "Financials",
    "BOKF": "Financials",
    "BOOT": "Consumer Discretionary",
    "BOX": "Information Technology",
    "BP": "Energy",
    "BPOP": "Financials",
    "BR": "Consumer Discretionary",
    "BRBR": "Consumer Staples",
    "BRKR": "Industrials",
    "BRO": "Financials",
    "BROS": "Consumer Discretionary",
    "BRSL": "Consumer Discretionary",
    "BRUN": "Information Technology",
    "BRX": "Real Estate",
    "BRZE": "Information Technology",
    "BSY": "Information Technology",
    "BTDR": "Financials",
    "BTG": "Materials",
    "BTI": "Health Care",
    "BTSG": "Health Care",
    "BTU": "Energy",
    "BUD": "Consumer Staples",
    "BULL": "Financials",
    "BURL": "Consumer Discretionary",
    "BUSE": "Financials",
    "BVN": "Materials",
    "BW": "Industrials",
    "BWA": "Consumer Discretionary",
    "BWIN": "Financials",
    "BWXT": "Industrials",
    "BXMT": "Real Estate",
    "BXP": "Real Estate",
    "BXSL": "Financials",
    "BYD": "Consumer Discretionary",
    "BZ": "Information Technology",
    "CACC": "Financials",
    "CACI": "Information Technology",
    "CAG": "Consumer Staples",
    "CAI": "Health Care",
    "CAKE": "Consumer Discretionary",
    "CALM": "Consumer Staples",
    "CALX": "Consumer Discretionary",
    "CALY": "Consumer Discretionary",
    "CAMT": "Information Technology",
    "CAPR": "Health Care",
    "CAR": "Consumer Discretionary",
    "CARG": "Information Technology",
    "CART": "Consumer Discretionary",
    "CASY": "Consumer Discretionary",
    "CATY": "Financials",
    "CAVA": "Consumer Discretionary",
    "CBC": "Financials",
    "CBOE": "Financials",
    "CBRE": "Financials",
    "CBRL": "Consumer Discretionary",
    "CBSH": "Financials",
    "CBT": "Industrials",
    "CBZ": "Consumer Discretionary",
    "CC": "Industrials",
    "CCC": "Information Technology",
    "CCEP": "Consumer Staples",
    "CCI": "Real Estate",
    "CCJ": "Materials",
    "CCK": "Industrials",
    "CCXI": "Financials",
    "CDE": "Materials",
    "CDNA": "Health Care",
    "CDNL": "Industrials",
    "CDP": "Real Estate",
    "CE": "Industrials",
    "CECO": "Industrials",
    "CELC": "Health Care",
    "CELH": "Consumer Staples",
    "CENX": "Industrials",
    "CERT": "Information Technology",
    "CEVA": "Information Technology",
    "CFG": "Financials",
    "CFR": "Financials",
    "CG": "Financials",
    "CGAU": "Materials",
    "CGNX": "Industrials",
    "CGON": "Health Care",
    "CHD": "Consumer Discretionary",
    "CHDN": "Consumer Discretionary",
    "CHE": "Health Care",
    "CHEF": "Consumer Discretionary",
    "CHH": "Consumer Discretionary",
    "CHKP": "Information Technology",
    "CHRD": "Energy",
    "CHRW": "Industrials",
    "CHWY": "Consumer Discretionary",
    "CHYM": "Financials",
    "CIEN": "Utilities",
    "CIFR": "Financials",
    "CIGI": "Financials",
    "CINF": "Financials",
    "CLBK": "Financials",
    "CLBT": "Information Technology",
    "CLDX": "Health Care",
    "CLF": "Materials",
    "CLH": "Industrials",
    "CLMT": "Energy",
    "CLS": "Information Technology",
    "CLSK": "Financials",
    "CLX": "Consumer Discretionary",
    "CLYM": "Health Care",
    "CM": "Financials",
    "CMC": "Industrials",
    "CMPS": "Health Care",
    "CMS": "Utilities",
    "CNA": "Financials",
    "CNC": "Health Care",
    "CNH": "Industrials",
    "CNI": "Industrials",
    "CNK": "Consumer Discretionary",
    "CNM": "Consumer Discretionary",
    "CNMD": "Health Care",
    "CNO": "Financials",
    "CNP": "Utilities",
    "CNQ": "Energy",
    "CNR": "Energy",
    "CNS": "Financials",
    "CNX": "Energy",
    "CNXC": "Information Technology",
    "COCO": "Consumer Staples",
    "COGT": "Health Care",
    "COHR": "Information Technology",
    "COHU": "Industrials",
    "COKE": "Consumer Staples",
    "COLB": "Financials",
    "COLD": "Real Estate",
    "COLL": "Health Care",
    "COLM": "Consumer Discretionary",
    "COMP": "Financials",
    "CON": "Health Care",
    "COO": "Health Care",
    "CORT": "Health Care",
    "CORZ": "Financials",
    "CP": "Industrials",
    "CPA": "Consumer Discretionary",
    "CPAY": "Consumer Discretionary",
    "CPB": "Consumer Staples",
    "CPK": "Utilities",
    "CPNG": "Consumer Discretionary",
    "CPRI": "Consumer Discretionary",
    "CPRT": "Consumer Discretionary",
    "CPT": "Real Estate",
    "CR": "Industrials",
    "CRAI": "Consumer Discretionary",
    "CRBG": "Financials",
    "CRC": "Energy",
    "CRCL": "Financials",
    "CRDO": "Information Technology",
    "CRGY": "Energy",
    "CRH": "Industrials",
    "CRI": "Consumer Discretionary",
    "CRK": "Energy",
    "CRL": "Health Care",
    "CRML": "Materials",
    "CROX": "Consumer Discretionary",
    "CRS": "Industrials",
    "CRSP": "Health Care",
    "CRUS": "Information Technology",
    "CRWV": "Information Technology",
    "CSGP": "Financials",
    "CSIQ": "Information Technology",
    "CSL": "Industrials",
    "CSTM": "Industrials",
    "CSW": "Industrials",
    "CTRE": "Real Estate",
    "CTRI": "Utilities",
    "CUBE": "Real Estate",
    "CUBI": "Financials",
    "CURB": "Financials",
    "CUZ": "Real Estate",
    "CVBF": "Financials",
    "CVCO": "Consumer Discretionary",
    "CVE": "Energy",
    "CVI": "Energy",
    "CVLT": "Information Technology",
    "CVNA": "Consumer Discretionary",
    "CVSA": "Real Estate",
    "CW": "Information Technology",
    "CWEN": "Utilities",
    "CWK": "Financials",
    "CWST": "Utilities",
    "CWT": "Utilities",
    "CX": "Industrials",
    "CXT": "Industrials",
    "CXW": "Real Estate",
    "CYTK": "Health Care",
    "CZR": "Consumer Discretionary",
    "D": "Utilities",
    "DAN": "Consumer Discretionary",
    "DAR": "Consumer Staples",
    "DAVE": "Financials",
    "DB": "Financials",
    "DBRG": "Real Estate",
    "DBX": "Information Technology",
    "DCI": "Industrials",
    "DCO": "Industrials",
    "DD": "Industrials",
    "DDS": "Consumer Discretionary",
    "DECK": "Consumer Discretionary",
    "DEI": "Real Estate",
    "DEO": "Consumer Staples",
    "DFTX": "Health Care",
    "DG": "Consumer Discretionary",
    "DGII": "Communication Services",
    "DGX": "Health Care",
    "DHI": "Consumer Discretionary",
    "DHT": "Consumer Discretionary",
    "DINO": "Energy",
    "DIOD": "Information Technology",
    "DJCO": "Consumer Discretionary",
    "DJT": "Information Technology",
    "DK": "Energy",
    "DKS": "Consumer Discretionary",
    "DLB": "Miscellaneous",
    "DLO": "Consumer Discretionary",
    "DNLI": "Health Care",
    "DNOW": "Consumer Discretionary",
    "DNTH": "Health Care",
    "DOC": "Real Estate",
    "DOCN": "Information Technology",
    "DOCS": "Information Technology",
    "DOCU": "Information Technology",
    "DORM": "Consumer Discretionary",
    "DOV": "Industrials",
    "DOW": "Industrials",
    "DOX": "Information Technology",
    "DPZ": "Consumer Discretionary",
    "DRH": "Real Estate",
    "DRI": "Consumer Discretionary",
    "DRS": "Industrials",
    "DSGX": "Information Technology",
    "DT": "Information Technology",
    "DTE": "Utilities",
    "DTM": "Utilities",
    "DUOL": "Information Technology",
    "DV": "Information Technology",
    "DVA": "Health Care",
    "DX": "Real Estate",
    "DXC": "Information Technology",
    "DXPE": "Industrials",
    "DY": "Industrials",
    "DYN": "Health Care",
    "EAT": "Consumer Discretionary",
    "EBC": "Financials",
    "EC": "Energy",
    "ECG": "Consumer Discretionary",
    "ECHO": "Consumer Discretionary",
    "ECO": "Consumer Discretionary",
    "ECPG": "Financials",
    "ED": "Utilities",
    "EDU": "Real Estate",
    "EEFT": "Financials",
    "EFOR": "Consumer Discretionary",
    "EFX": "Financials",
    "EG": "Financials",
    "EGO": "Materials",
    "EGP": "Real Estate",
    "EHC": "Health Care",
    "EIX": "Utilities",
    "ELAN": "Health Care",
    "ELF": "Consumer Discretionary",
    "ELS": "Real Estate",
    "ELVN": "Health Care",
    "EMBJ": "Industrials",
    "EMN": "Industrials",
    "ENB": "Energy",
    "ENOV": "Health Care",
    "ENPH": "Information Technology",
    "ENR": "Miscellaneous",
    "ENS": "Miscellaneous",
    "ENSG": "Health Care",
    "ENTG": "Industrials",
    "ENVA": "Financials",
    "EPAM": "Information Technology",
    "EPD": "Utilities",
    "EPR": "Real Estate",
    "EPRT": "Real Estate",
    "EQH": "Financials",
    "EQNR": "Energy",
    "EQPT": "Consumer Discretionary",
    "EQX": "Materials",
    "ERAS": "Health Care",
    "ERIC": "Information Technology",
    "ERIE": "Financials",
    "ERO": "Materials",
    "ES": "Utilities",
    "ESAB": "Industrials",
    "ESE": "Communication Services",
    "ESI": "Industrials",
    "ESLT": "Industrials",
    "ESNT": "Financials",
    "ESQ": "Financials",
    "ESS": "Real Estate",
    "ESTA": "Health Care",
    "ESTC": "Information Technology",
    "ETON": "Health Care",
    "ETOR": "Financials",
    "ETR": "Utilities",
    "ETSY": "Consumer Discretionary",
    "EVR": "Financials",
    "EVRG": "Utilities",
    "EW": "Health Care",
    "EWBC": "Financials",
    "EWTX": "Health Care",
    "EXC": "Utilities",
    "EXE": "Energy",
    "EXEL": "Health Care",
    "EXK": "Materials",
    "EXLS": "Consumer Discretionary",
    "EXP": "Industrials",
    "EXPD": "Industrials",
    "EXPO": "Consumer Discretionary",
    "EXR": "Real Estate",
    "EXTR": "Communication Services",
    "EYE": "Health Care",
    "EZPW": "Consumer Discretionary",
    "FA": "Information Technology",
    "FAF": "Financials",
    "FBIN": "Materials",
    "FBK": "Financials",
    "FBP": "Financials",
    "FCEL": "Energy",
    "FCF": "Financials",
    "FCFS": "Consumer Discretionary",
    "FCN": "Consumer Discretionary",
    "FCNCA": "Financials",
    "FCPT": "Real Estate",
    "FDS": "Information Technology",
    "FE": "Utilities",
    "FEIM": "Industrials",
    "FELE": "Consumer Discretionary",
    "FER": "Industrials",
    "FERG": "Miscellaneous",
    "FFBC": "Financials",
    "FFIN": "Financials",
    "FFIV": "Communication Services",
    "FHB": "Financials",
    "FHI": "Financials",
    "FHN": "Financials",
    "FIBK": "Financials",
    "FICO": "Consumer Discretionary",
    "FIG": "Information Technology",
    "FIGR": "Financials",
    "FIGS": "Consumer Discretionary",
    "FIS": "Consumer Discretionary",
    "FISV": "Consumer Discretionary",
    "FIVE": "Consumer Discretionary",
    "FIVN": "Information Technology",
    "FIX": "Industrials",
    "FLG": "Financials",
    "FLNC": "Miscellaneous",
    "FLO": "Consumer Staples",
    "FLR": "Industrials",
    "FLS": "Industrials",
    "FLUT": "Information Technology",
    "FLY": "Industrials",
    "FLYW": "Consumer Discretionary",
    "FMC": "Industrials",
    "FMX": "Consumer Staples",
    "FN": "Utilities",
    "FNB": "Financials",
    "FND": "Consumer Discretionary",
    "FNF": "Financials",
    "FNV": "Materials",
    "FORM": "Information Technology",
    "FOUR": "Consumer Discretionary",
    "FOX": "Industrials",
    "FPS": "Energy",
    "FR": "Real Estate",
    "FRO": "Consumer Discretionary",
    "FROG": "Information Technology",
    "FRPT": "Consumer Staples",
    "FRSH": "Information Technology",
    "FRT": "Real Estate",
    "FSK": "Financials",
    "FSLY": "Information Technology",
    "FSM": "Materials",
    "FSS": "Industrials",
    "FSV": "Financials",
    "FTAI": "Industrials",
    "FTDR": "Consumer Discretionary",
    "FTI": "Consumer Discretionary",
    "FTRE": "Health Care",
    "FTS": "Utilities",
    "FTV": "Industrials",
    "FUL": "Industrials",
    "FULT": "Financials",
    "FUN": "Consumer Discretionary",
    "FUTU": "Financials",
    "FWONK": "Industrials",
    "G": "Consumer Discretionary",
    "GAP": "Consumer Discretionary",
    "GATX": "Consumer Discretionary",
    "GBCI": "Financials",
    "GCT": "Consumer Discretionary",
    "GDDY": "Information Technology",
    "GDS": "Information Technology",
    "GEHC": "Health Care",
    "GEN": "Information Technology",
    "GENI": "Consumer Discretionary",
    "GEO": "Consumer Discretionary",
    "GEV": "Information Technology",
    "GFF": "Industrials",
    "GFI": "Materials",
    "GFL": "Utilities",
    "GFS": "Information Technology",
    "GGAL": "Financials",
    "GGG": "Industrials",
    "GH": "Health Care",
    "GHC": "Real Estate",
    "GHM": "Industrials",
    "GIB": "Consumer Discretionary",
    "GIL": "Consumer Discretionary",
    "GKOS": "Health Care",
    "GL": "Financials",
    "GLBE": "Information Technology",
    "GLNG": "Consumer Discretionary",
    "GLOB": "Information Technology",
    "GLPI": "Real Estate",
    "GLXY": "Financials",
    "GMAB": "Health Care",
    "GME": "Consumer Discretionary",
    "GMED": "Health Care",
    "GNL": "Real Estate",
    "GNRC": "Consumer Discretionary",
    "GNTX": "Consumer Discretionary",
    "GNW": "Financials",
    "GO": "Consumer Staples",
    "GOF": "Financials",
    "GOLD": "Industrials",
    "GOLF": "Consumer Discretionary",
    "GPC": "Consumer Discretionary",
    "GPCR": "Health Care",
    "GPGI": "Financials",
    "GPI": "Consumer Discretionary",
    "GPK": "Consumer Discretionary",
    "GPOR": "Energy",
    "GPRE": "Industrials",
    "GRAL": "Health Care",
    "GRMN": "Industrials",
    "GRND": "Information Technology",
    "GRPN": "Consumer Discretionary",
    "GSAT": "Consumer Discretionary",
    "GSHD": "Financials",
    "GSK": "Health Care",
    "GT": "Consumer Discretionary",
    "GTES": "Industrials",
    "GTLB": "Information Technology",
    "GTX": "Consumer Discretionary",
    "GVA": "Industrials",
    "GWRE": "Information Technology",
    "GXO": "Consumer Discretionary",
    "H": "Consumer Discretionary",
    "HAE": "Health Care",
    "HALO": "Health Care",
    "HAPN": "Financials",
    "HAS": "Consumer Discretionary",
    "HASI": "Financials",
    "HAYW": "Industrials",
    "HBM": "Materials",
    "HCC": "Energy",
    "HCI": "Financials",
    "HDB": "Financials",
    "HE": "Utilities",
    "HEI": "Industrials",
    "HESM": "Energy",
    "HGV": "Consumer Discretionary",
    "HHH": "Real Estate",
    "HIG": "Financials",
    "HII": "Industrials",
    "HIMS": "Health Care",
    "HIW": "Real Estate",
    "HL": "Industrials",
    "HLI": "Financials",
    "HLIO": "Industrials",
    "HLN": "Consumer Discretionary",
    "HLNE": "Financials",
    "HMC": "Industrials",
    "HMY": "Materials",
    "HNGE": "Information Technology",
    "HNI": "Consumer Discretionary",
    "HOG": "Consumer Discretionary",
    "HOMB": "Financials",
    "HP": "Energy",
    "HQY": "Consumer Discretionary",
    "HR": "Real Estate",
    "HRB": "Consumer Discretionary",
    "HRI": "Industrials",
    "HRL": "Consumer Staples",
    "HRMY": "Health Care",
    "HROW": "Health Care",
    "HSAI": "Industrials",
    "HSBC": "Financials",
    "HSIC": "Health Care",
    "HST": "Real Estate",
    "HSY": "Consumer Staples",
    "HTFL": "Health Care",
    "HTGC": "Financials",
    "HTHT": "Consumer Discretionary",
    "HTO": "Utilities",
    "HUBB": "Information Technology",
    "HUBG": "Industrials",
    "HUN": "Industrials",
    "HURN": "Consumer Discretionary",
    "HUT": "Financials",
    "HWC": "Financials",
    "HWKN": "Consumer Discretionary",
    "HXL": "Industrials",
    "HYMC": "Materials",
    "HZO": "Consumer Discretionary",
    "IAG": "Materials",
    "IBKR": "Financials",
    "IBN": "Financials",
    "IBOC": "Financials",
    "IBP": "Consumer Discretionary",
    "IBRX": "Health Care",
    "ICHR": "Information Technology",
    "ICLR": "Health Care",
    "ICUI": "Health Care",
    "IDA": "Utilities",
    "IDCC": "Miscellaneous",
    "IDYA": "Health Care",
    "IE": "Materials",
    "IESC": "Industrials",
    "IEX": "Industrials",
    "IFF": "Industrials",
    "IHG": "Consumer Discretionary",
    "IIPR": "Financials",
    "IMAX": "Consumer Discretionary",
    "IMNM": "Health Care",
    "IMO": "Energy",
    "IMVT": "Health Care",
    "INBX": "Health Care",
    "INCY": "Health Care",
    "INDB": "Financials",
    "INDV": "Health Care",
    "INFQ": "Information Technology",
    "INFY": "Information Technology",
    "ING": "Financials",
    "INGM": "Information Technology",
    "INGR": "Consumer Staples",
    "INOD": "Information Technology",
    "INSM": "Health Care",
    "INSP": "Health Care",
    "INSW": "Consumer Discretionary",
    "INTA": "Information Technology",
    "INTR": "Financials",
    "INVH": "Financials",
    "IONQ": "Information Technology",
    "IONS": "Health Care",
    "IOT": "Information Technology",
    "IOVA": "Health Care",
    "IP": "Materials",
    "IPAR": "Consumer Discretionary",
    "IPGP": "Information Technology",
    "IRDM": "Consumer Discretionary",
    "IREN": "Financials",
    "IRM": "Real Estate",
    "IRON": "Health Care",
    "IRT": "Real Estate",
    "IRTC": "Health Care",
    "ITGR": "Health Care",
    "ITRI": "Industrials",
    "ITT": "Industrials",
    "ITW": "Industrials",
    "IVR": "Real Estate",
    "IVT": "Real Estate",
    "IVZ": "Financials",
    "J": "Industrials",
    "JAZZ": "Health Care",
    "JBHT": "Industrials",
    "JBS": "Consumer Staples",
    "JBTM": "Industrials",
    "JD": "Consumer Discretionary",
    "JEF": "Financials",
    "JHX": "Industrials",
    "JKHY": "Information Technology",
    "JLL": "Financials",
    "JOBY": "Industrials",
    "JOYY": "Information Technology",
    "JXN": "Financials",
    "KAI": "Industrials",
    "KALU": "Industrials",
    "KB": "Financials",
    "KBH": "Consumer Discretionary",
    "KBR": "Industrials",
    "KD": "Information Technology",
    "KEX": "Consumer Discretionary",
    "KEY": "Financials",
    "KFY": "Consumer Discretionary",
    "KGC": "Materials",
    "KGS": "Utilities",
    "KIM": "Real Estate",
    "KLAR": "Financials",
    "KLIC": "Information Technology",
    "KMPR": "Financials",
    "KMT": "Industrials",
    "KMX": "Consumer Discretionary",
    "KN": "Consumer Staples",
    "KNF": "Industrials",
    "KNSA": "Health Care",
    "KNSL": "Financials",
    "KNTK": "Utilities",
    "KNX": "Industrials",
    "KOD": "Health Care",
    "KRC": "Real Estate",
    "KRG": "Real Estate",
    "KRMN": "Industrials",
    "KRYS": "Health Care",
    "KSS": "Consumer Discretionary",
    "KT": "Communication Services",
    "KTB": "Industrials",
    "KTOS": "Industrials",
    "KURA": "Health Care",
    "KVYO": "Information Technology",
    "KWR": "Industrials",
    "KYMR": "Health Care",
    "L": "Financials",
    "LAD": "Consumer Discretionary",
    "LAMR": "Real Estate",
    "LASR": "Information Technology",
    "LAUR": "Real Estate",
    "LAZ": "Financials",
    "LB": "Energy",
    "LBRT": "Energy",
    "LBTYA": "Communication Services",
    "LCII": "Consumer Discretionary",
    "LDOS": "Information Technology",
    "LEA": "Consumer Discretionary",
    "LECO": "Industrials",
    "LEGN": "Health Care",
    "LEN": "Consumer Discretionary",
    "LEU": "Industrials",
    "LEVI": "Consumer Discretionary",
    "LFST": "Health Care",
    "LFUS": "Energy",
    "LGN": "Consumer Discretionary",
    "LGND": "Health Care",
    "LH": "Health Care",
    "LI": "Industrials",
    "LIF": "Information Technology",
    "LIFE": "Financials",
    "LII": "Industrials",
    "LINC": "Real Estate",
    "LIND": "Consumer Discretionary",
    "LINE": "Real Estate",
    "LION": "Consumer Discretionary",
    "LITE": "Communication Services",
    "LIVN": "Health Care",
    "LKQ": "Consumer Discretionary",
    "LLYVK": "Consumer Discretionary",
    "LMAT": "Health Care",
    "LMND": "Financials",
    "LNC": "Financials",
    "LNT": "Utilities",
    "LNTH": "Health Care",
    "LOAR": "Industrials",
    "LOGI": "Information Technology",
    "LOPE": "Real Estate",
    "LPG": "Consumer Discretionary",
    "LPLA": "Financials",
    "LPTH": "Information Technology",
    "LPX": "Materials",
    "LQDA": "Health Care",
    "LRN": "Real Estate",
    "LSCC": "Information Technology",
    "LSTR": "Industrials",
    "LTC": "Real Estate",
    "LTH": "Consumer Discretionary",
    "LTM": "Consumer Discretionary",
    "LUMN": "Communication Services",
    "LUNR": "Industrials",
    "LUV": "Consumer Discretionary",
    "LVS": "Consumer Discretionary",
    "LW": "Consumer Staples",
    "LXP": "Real Estate",
    "LYB": "Industrials",
    "LYFT": "Consumer Discretionary",
    "LYG": "Financials",
    "LZB": "Consumer Discretionary",
    "M": "Consumer Discretionary",
    "MAA": "Real Estate",
    "MAC": "Real Estate",
    "MAIN": "Financials",
    "MAN": "Consumer Discretionary",
    "MANE": "Health Care",
    "MANH": "Information Technology",
    "MARA": "Financials",
    "MAS": "Industrials",
    "MAT": "Consumer Discretionary",
    "MATX": "Consumer Discretionary",
    "MBLY": "Information Technology",
    "MBX": "Health Care",
    "MC": "Financials",
    "MCY": "Financials",
    "MD": "Health Care",
    "MDGL": "Health Care",
    "MDLN": "Health Care",
    "MDU": "Industrials",
    "MEDP": "Health Care",
    "MELI": "Consumer Discretionary",
    "MEOH": "Industrials",
    "METC": "Energy",
    "MFC": "Financials",
    "MFG": "Financials",
    "MGA": "Consumer Discretionary",
    "MGM": "Consumer Discretionary",
    "MGNI": "Information Technology",
    "MGY": "Energy",
    "MHK": "Consumer Discretionary",
    "MHO": "Consumer Discretionary",
    "MIAX": "Financials",
    "MIDD": "Industrials",
    "MIR": "Industrials",
    "MIRM": "Health Care",
    "MKC": "Consumer Staples",
    "MKL": "Financials",
    "MKSI": "Industrials",
    "MKTX": "Financials",
    "MLI": "Industrials",
    "MLTX": "Health Care",
    "MLYS": "Health Care",
    "MMED": "Health Care",
    "MMM": "Health Care",
    "MMS": "Consumer Discretionary",
    "MMSI": "Health Care",
    "MMYT": "Consumer Discretionary",
    "MNDY": "Information Technology",
    "MNPR": "Health Care",
    "MOD": "Consumer Discretionary",
    "MOH": "Health Care",
    "MORN": "Financials",
    "MOS": "Industrials",
    "MP": "Materials",
    "MRCY": "Information Technology",
    "MRP": "Financials",
    "MRSH": "Financials",
    "MRX": "Financials",
    "MSA": "Health Care",
    "MSGE": "Consumer Discretionary",
    "MSGS": "Consumer Discretionary",
    "MSM": "Industrials",
    "MSTR": "Information Technology",
    "MT": "Industrials",
    "MTB": "Financials",
    "MTCH": "Information Technology",
    "MTD": "Industrials",
    "MTDR": "Energy",
    "MTG": "Financials",
    "MTH": "Consumer Discretionary",
    "MTN": "Consumer Discretionary",
    "MTRN": "Industrials",
    "MTSI": "Information Technology",
    "MTZ": "Industrials",
    "MUFG": "Financials",
    "MUR": "Energy",
    "MUSA": "Consumer Discretionary",
    "MWA": "Industrials",
    "MWH": "Industrials",
    "MXL": "Information Technology",
    "MYRG": "Industrials",
    "MZTI": "Consumer Staples",
    "NAMS": "Health Care",
    "NAT": "Consumer Discretionary",
    "NATL": "Miscellaneous",
    "NAVN": "Information Technology",
    "NBIS": "Information Technology",
    "NBIX": "Health Care",
    "NBR": "Energy",
    "NCLH": "Consumer Discretionary",
    "NCNO": "Information Technology",
    "NDAQ": "Financials",
    "NDSN": "Industrials",
    "NE": "Energy",
    "NEO": "Health Care",
    "NEOG": "Health Care",
    "NESR": "Energy",
    "NEU": "Industrials",
    "NFG": "Utilities",
    "NG": "Materials",
    "NGG": "Utilities",
    "NHC": "Health Care",
    "NHI": "Real Estate",
    "NI": "Utilities",
    "NIC": "Financials",
    "NICE": "Information Technology",
    "NIQ": "Information Technology",
    "NJR": "Utilities",
    "NKTR": "Health Care",
    "NLY": "Real Estate",
    "NMIH": "Financials",
    "NMRK": "Financials",
    "NN": "Industrials",
    "NNE": "Utilities",
    "NNN": "Real Estate",
    "NOG": "Energy",
    "NOK": "Information Technology",
    "NOV": "Consumer Discretionary",
    "NOVT": "Miscellaneous",
    "NPO": "Industrials",
    "NRIX": "Health Care",
    "NSIT": "Consumer Discretionary",
    "NSP": "Consumer Discretionary",
    "NTAP": "Information Technology",
    "NTCT": "Information Technology",
    "NTES": "Information Technology",
    "NTLA": "Health Care",
    "NTNX": "Information Technology",
    "NTR": "Industrials",
    "NTRA": "Health Care",
    "NTRS": "Financials",
    "NTSK": "Information Technology",
    "NTST": "Real Estate",
    "NU": "Financials",
    "NUAI": "Energy",
    "NUTX": "Consumer Discretionary",
    "NUVB": "Health Care",
    "NVAX": "Health Care",
    "NVCR": "Health Care",
    "NVMI": "Information Technology",
    "NVO": "Health Care",
    "NVR": "Consumer Discretionary",
    "NVS": "Health Care",
    "NVST": "Health Care",
    "NVT": "Industrials",
    "NVTS": "Information Technology",
    "NWE": "Utilities",
    "NWG": "Financials",
    "NWL": "Industrials",
    "NWS": "Consumer Discretionary",
    "NWSA": "Consumer Discretionary",
    "NXE": "Materials",
    "NXST": "Industrials",
    "NXT": "Information Technology",
    "NYT": "Consumer Discretionary",
    "OBDC": "Financials",
    "OC": "Industrials",
    "OCUL": "Health Care",
    "OGE": "Utilities",
    "OGN": "Health Care",
    "OGS": "Utilities",
    "OHI": "Real Estate",
    "OI": "Consumer Discretionary",
    "OII": "Energy",
    "OKLO": "Utilities",
    "OKTA": "Information Technology",
    "OLED": "Information Technology",
    "OLLI": "Consumer Discretionary",
    "OLN": "Industrials",
    "OMC": "Consumer Discretionary",
    "OMCL": "Information Technology",
    "OMDA": "Health Care",
    "OMER": "Health Care",
    "OMF": "Financials",
    "ONB": "Financials",
    "ONC": "Health Care",
    "ONDS": "Information Technology",
    "ONON": "Consumer Discretionary",
    "ONTO": "Industrials",
    "OPCH": "Health Care",
    "OPLN": "Consumer Discretionary",
    "OR": "Materials",
    "ORA": "Utilities",
    "ORC": "Real Estate",
    "ORI": "Financials",
    "ORKA": "Health Care",
    "OSCR": "Health Care",
    "OSIS": "Information Technology",
    "OSK": "Industrials",
    "OSW": "Consumer Discretionary",
    "OTEX": "Information Technology",
    "OTIS": "Information Technology",
    "OTTR": "Utilities",
    "OUST": "Industrials",
    "OUT": "Real Estate",
    "OVV": "Energy",
    "OWL": "Financials",
    "OZK": "Financials",
    "P": "Information Technology",
    "PAAS": "Materials",
    "PAC": "Consumer Discretionary",
    "PACS": "Health Care",
    "PAG": "Consumer Discretionary",
    "PAGS": "Information Technology",
    "PARR": "Energy",
    "PATH": "Information Technology",
    "PATK": "Consumer Discretionary",
    "PAY": "Consumer Discretionary",
    "PAYC": "Information Technology",
    "PAYO": "Consumer Discretionary",
    "PAYX": "Industrials",
    "PB": "Financials",
    "PBA": "Energy",
    "PBF": "Energy",
    "PBH": "Health Care",
    "PBI": "Miscellaneous",
    "PBR": "Energy",
    "PCG": "Utilities",
    "PCOR": "Information Technology",
    "PCTY": "Information Technology",
    "PCVX": "Health Care",
    "PDD": "Consumer Discretionary",
    "PDFS": "Information Technology",
    "PDI": "Financials",
    "PEB": "Real Estate",
    "PECO": "Real Estate",
    "PEG": "Utilities",
    "PEGA": "Information Technology",
    "PEN": "Health Care",
    "PENG": "Information Technology",
    "PENN": "Consumer Discretionary",
    "PFG": "Financials",
    "PFGC": "Consumer Discretionary",
    "PFS": "Financials",
    "PFSI": "Financials",
    "PGEN": "Health Care",
    "PGNY": "Health Care",
    "PGY": "Financials",
    "PHG": "Health Care",
    "PHIN": "Consumer Discretionary",
    "PHM": "Consumer Discretionary",
    "PHVS": "Health Care",
    "PI": "Information Technology",
    "PII": "Consumer Discretionary",
    "PINS": "Information Technology",
    "PIPR": "Financials",
    "PJT": "Financials",
    "PK": "Consumer Discretionary",
    "PKG": "Consumer Discretionary",
    "PL": "Information Technology",
    "PLAB": "Information Technology",
    "PLMR": "Financials",
    "PLNT": "Consumer Discretionary",
    "PLPC": "Industrials",
    "PLSE": "Health Care",
    "PLUS": "Information Technology",
    "PLXS": "Information Technology",
    "PNFP": "Financials",
    "PNR": "Industrials",
    "PNW": "Utilities",
    "PODD": "Health Care",
    "POET": "Information Technology",
    "PONY": "Information Technology",
    "POOL": "Consumer Discretionary",
    "POR": "Utilities",
    "POST": "Consumer Staples",
    "POWI": "Information Technology",
    "POWL": "Energy",
    "PPC": "Consumer Staples",
    "PPG": "Consumer Discretionary",
    "PPLI": "Information Technology",
    "PPTA": "Materials",
    "PR": "Energy",
    "PRAX": "Health Care",
    "PRCH": "Information Technology",
    "PRCT": "Health Care",
    "PRDO": "Real Estate",
    "PRG": "Consumer Discretionary",
    "PRGO": "Health Care",
    "PRGS": "Information Technology",
    "PRI": "Financials",
    "PRIM": "Industrials",
    "PRKS": "Consumer Discretionary",
    "PRM": "Industrials",
    "PRMB": "Consumer Staples",
    "PRU": "Financials",
    "PRVA": "Health Care",
    "PSA": "Real Estate",
    "PSKY": "Industrials",
    "PSMT": "Consumer Discretionary",
    "PSN": "Information Technology",
    "PSNL": "Health Care",
    "PTC": "Information Technology",
    "PTCT": "Health Care",
    "PTEN": "Energy",
    "PTGX": "Health Care",
    "PTRN": "Consumer Discretionary",
    "PUK": "Financials",
    "PUMP": "Energy",
    "PURR": "Financials",
    "PVH": "Industrials",
    "PVLA": "Health Care",
    "PZZA": "Consumer Discretionary",
    "Q": "Information Technology",
    "QBTS": "Information Technology",
    "QDEL": "Health Care",
    "QGEN": "Health Care",
    "QLYS": "Information Technology",
    "QMCO": "Information Technology",
    "QRVO": "Information Technology",
    "QSR": "Consumer Discretionary",
    "QTWO": "Information Technology",
    "QUBT": "Information Technology",
    "QURE": "Health Care",
    "QXO": "Consumer Discretionary",
    "R": "Consumer Discretionary",
    "RACE": "Industrials",
    "RAL": "Industrials",
    "RAMP": "Information Technology",
    "RARE": "Health Care",
    "RBA": "Consumer Discretionary",
    "RBC": "Industrials",
    "RBRK": "Information Technology",
    "RCAT": "Information Technology",
    "RCI": "Communication Services",
    "RCUS": "Health Care",
    "RDDT": "Information Technology",
    "RDN": "Financials",
    "RDNT": "Health Care",
    "RDW": "Industrials",
    "RDY": "Health Care",
    "REAL": "Consumer Discretionary",
    "REG": "Real Estate",
    "RELX": "Consumer Discretionary",
    "RELY": "Consumer Discretionary",
    "REPL": "Health Care",
    "REXR": "Real Estate",
    "REYN": "Consumer Discretionary",
    "REZI": "Industrials",
    "RF": "Financials",
    "RGA": "Financials",
    "RGEN": "Health Care",
    "RGLD": "Industrials",
    "RGTI": "Information Technology",
    "RH": "Consumer Discretionary",
    "RHI": "Consumer Discretionary",
    "RHLD": "Financials",
    "RHP": "Real Estate",
    "RIG": "Energy",
    "RIO": "Materials",
    "RIOT": "Financials",
    "RITM": "Real Estate",
    "RJF": "Financials",
    "RKLB": "Industrials",
    "RKT": "Financials",
    "RL": "Industrials",
    "RLAY": "Health Care",
    "RLI": "Financials",
    "RLJ": "Real Estate",
    "RMBS": "Information Technology",
    "RNG": "Information Technology",
    "RNR": "Financials",
    "RNST": "Financials",
    "ROAD": "Industrials",
    "ROG": "Industrials",
    "ROIV": "Health Care",
    "ROKU": "Communication Services",
    "ROL": "Consumer Discretionary",
    "RPD": "Information Technology",
    "RPM": "Consumer Discretionary",
    "RPRX": "Health Care",
    "RRC": "Energy",
    "RRR": "Consumer Discretionary",
    "RRX": "Industrials",
    "RS": "Industrials",
    "RSI": "Consumer Discretionary",
    "RTO": "Consumer Discretionary",
    "RUM": "Information Technology",
    "RUN": "Miscellaneous",
    "RUSHA": "Consumer Discretionary",
    "RVLV": "Consumer Discretionary",
    "RVMD": "Health Care",
    "RVTY": "Industrials",
    "RXO": "Consumer Discretionary",
    "RY": "Financials",
    "RYAAY": "Consumer Discretionary",
    "RYAN": "Financials",
    "RYN": "Real Estate",
    "RYTM": "Health Care",
    "S": "Information Technology",
    "SAH": "Consumer Discretionary",
    "SAIA": "Industrials",
    "SAIC": "Information Technology",
    "SAIL": "Information Technology",
    "SAM": "Consumer Staples",
    "SAN": "Financials",
    "SANM": "Information Technology",
    "SAP": "Information Technology",
    "SARO": "Industrials",
    "SATL": "Information Technology",
    "SBAC": "Real Estate",
    "SBCF": "Financials",
    "SBET": "Information Technology",
    "SBH": "Consumer Discretionary",
    "SBLK": "Consumer Discretionary",
    "SBRA": "Real Estate",
    "SBS": "Utilities",
    "SBSW": "Materials",
    "SCCO": "Materials",
    "SCI": "Consumer Discretionary",
    "SDRL": "Energy",
    "SE": "Consumer Discretionary",
    "SEB": "Industrials",
    "SEDG": "Information Technology",
    "SEI": "Consumer Discretionary",
    "SEIC": "Financials",
    "SEZL": "Financials",
    "SF": "Financials",
    "SFBS": "Financials",
    "SFD": "Consumer Staples",
    "SFM": "Consumer Staples",
    "SFNC": "Financials",
    "SG": "Consumer Discretionary",
    "SGHC": "Consumer Discretionary",
    "SGI": "Consumer Discretionary",
    "SGRY": "Health Care",
    "SHAK": "Consumer Discretionary",
    "SHAZ": "Information Technology",
    "SHC": "Health Care",
    "SHEL": "Energy",
    "SHLS": "Information Technology",
    "SHO": "Consumer Discretionary",
    "SHOO": "Consumer Discretionary",
    "SHOP": "Information Technology",
    "SIG": "Consumer Discretionary",
    "SIGI": "Financials",
    "SII": "Financials",
    "SIMO": "Information Technology",
    "SIRI": "Consumer Discretionary",
    "SITE": "Consumer Discretionary",
    "SITM": "Information Technology",
    "SJM": "Consumer Staples",
    "SKM": "Communication Services",
    "SKT": "Real Estate",
    "SKWD": "Financials",
    "SKY": "Consumer Discretionary",
    "SKYW": "Consumer Discretionary",
    "SLAB": "Information Technology",
    "SLDE": "Financials",
    "SLF": "Financials",
    "SLG": "Real Estate",
    "SLGN": "Industrials",
    "SLM": "Financials",
    "SLS": "Health Care",
    "SM": "Energy",
    "SMA": "Real Estate",
    "SMFG": "Financials",
    "SMG": "Industrials",
    "SMMT": "Health Care",
    "SMPL": "Consumer Staples",
    "SMR": "Industrials",
    "SMTC": "Information Technology",
    "SN": "Consumer Discretionary",
    "SNA": "Consumer Discretionary",
    "SNAP": "Information Technology",
    "SNDK": "Information Technology",
    "SNDR": "Industrials",
    "SNDX": "Health Care",
    "SNEX": "Financials",
    "SNN": "Health Care",
    "SNX": "Information Technology",
    "SNY": "Health Care",
    "SOBO": "Energy",
    "SOFI": "Financials",
    "SOLS": "Industrials",
    "SOLV": "Health Care",
    "SON": "Consumer Discretionary",
    "SONO": "Consumer Staples",
    "SONY": "Consumer Staples",
    "SOUN": "Information Technology",
    "SPB": "Miscellaneous",
    "SPG": "Real Estate",
    "SPHR": "Consumer Discretionary",
    "SPSC": "Information Technology",
    "SPXC": "Industrials",
    "SQM": "Industrials",
    "SR": "Utilities",
    "SRAD": "Information Technology",
    "SRPT": "Health Care",
    "SRRK": "Health Care",
    "SSB": "Financials",
    "SSD": "Consumer Discretionary",
    "SSNC": "Information Technology",
    "SSRM": "Industrials",
    "ST": "Industrials",
    "STAA": "Health Care",
    "STAG": "Real Estate",
    "STE": "Health Care",
    "STEP": "Financials",
    "STM": "Information Technology",
    "STN": "Consumer Discretionary",
    "STNE": "Information Technology",
    "STNG": "Consumer Discretionary",
    "STOK": "Health Care",
    "STRA": "Real Estate",
    "STRL": "Industrials",
    "STT": "Financials",
    "STUB": "Consumer Discretionary",
    "STWD": "Real Estate",
    "STZ": "Consumer Staples",
    "SU": "Energy",
    "SUI": "Real Estate",
    "SUNB": "Consumer Discretionary",
    "SUPN": "Health Care",
    "SUZ": "Materials",
    "SVM": "Materials",
    "SW": "Consumer Discretionary",
    "SWK": "Consumer Discretionary",
    "SWX": "Utilities",
    "SXI": "Industrials",
    "SXT": "Industrials",
    "SYF": "Financials",
    "SYM": "Industrials",
    "SYNA": "Information Technology",
    "SYRE": "Health Care",
    "SYY": "Consumer Discretionary",
    "TAC": "Utilities",
    "TAK": "Health Care",
    "TAL": "Real Estate",
    "TALO": "Energy",
    "TAP": "Consumer Staples",
    "TARS": "Health Care",
    "TBBB": "Consumer Staples",
    "TBBK": "Financials",
    "TCBI": "Financials",
    "TCOM": "Consumer Discretionary",
    "TD": "Financials",
    "TDC": "Information Technology",
    "TDOC": "Health Care",
    "TDS": "Communication Services",
    "TDW": "Consumer Discretionary",
    "TDY": "Industrials",
    "TECH": "Health Care",
    "TECK": "Industrials",
    "TEM": "Information Technology",
    "TENB": "Information Technology",
    "TEX": "Industrials",
    "TFII": "Industrials",
    "TFX": "Health Care",
    "TGB": "Materials",
    "TGTX": "Health Care",
    "TH": "Consumer Discretionary",
    "THC": "Health Care",
    "THG": "Financials",
    "THO": "Industrials",
    "TIGO": "Communication Services",
    "TKO": "Consumer Discretionary",
    "TKR": "Industrials",
    "TLN": "Utilities",
    "TM": "Industrials",
    "TMDX": "Health Care",
    "TME": "Consumer Discretionary",
    "TNDM": "Health Care",
    "TNET": "Consumer Discretionary",
    "TNGX": "Health Care",
    "TNK": "Consumer Discretionary",
    "TNL": "Consumer Discretionary",
    "TOL": "Consumer Discretionary",
    "TOST": "Information Technology",
    "TOWN": "Financials",
    "TPB": "Consumer Discretionary",
    "TPC": "Consumer Discretionary",
    "TPG": "Financials",
    "TPL": "Energy",
    "TREX": "Materials",
    "TRI": "Consumer Discretionary",
    "TRIP": "Information Technology",
    "TRMB": "Industrials",
    "TRN": "Industrials",
    "TRNO": "Financials",
    "TROW": "Financials",
    "TRP": "Utilities",
    "TRU": "Financials",
    "TRVI": "Health Care",
    "TS": "Industrials",
    "TSEM": "Information Technology",
    "TSM": "Information Technology",
    "TSN": "Consumer Staples",
    "TTAN": "Information Technology",
    "TTC": "Consumer Discretionary",
    "TTE": "Energy",
    "TTEK": "Consumer Discretionary",
    "TTMI": "Information Technology",
    "TU": "Communication Services",
    "TVTX": "Health Care",
    "TW": "Financials",
    "TWLO": "Information Technology",
    "TWST": "Health Care",
    "TX": "Industrials",
    "TXG": "Industrials",
    "TXNM": "Utilities",
    "TXRH": "Consumer Discretionary",
    "TXT": "Industrials",
    "TYL": "Information Technology",
    "U": "Information Technology",
    "UBS": "Financials",
    "UBSI": "Financials",
    "UCB": "Financials",
    "UCTT": "Information Technology",
    "UDR": "Real Estate",
    "UEC": "Materials",
    "UFPI": "Materials",
    "UFPT": "Health Care",
    "UGI": "Utilities",
    "UGP": "Utilities",
    "UHS": "Health Care",
    "UI": "Information Technology",
    "UL": "Consumer Discretionary",
    "ULS": "Health Care",
    "UMAC": "Information Technology",
    "UMBF": "Financials",
    "UMC": "Information Technology",
    "UNF": "Consumer Discretionary",
    "UNFI": "Consumer Discretionary",
    "UNIT": "Real Estate",
    "UNM": "Financials",
    "UPST": "Financials",
    "UPWK": "Information Technology",
    "URBN": "Consumer Discretionary",
    "URGN": "Health Care",
    "USAR": "Materials",
    "USFD": "Consumer Discretionary",
    "UTHR": "Health Care",
    "UTI": "Real Estate",
    "UTZ": "Consumer Staples",
    "UUUU": "Industrials",
    "VAC": "Financials",
    "VAL": "Energy",
    "VALE": "Materials",
    "VC": "Consumer Discretionary",
    "VCEL": "Health Care",
    "VCTR": "Financials",
    "VCYT": "Health Care",
    "VECO": "Information Technology",
    "VEEV": "Information Technology",
    "VERA": "Health Care",
    "VERX": "Information Technology",
    "VFC": "Industrials",
    "VG": "Utilities",
    "VIAV": "Information Technology",
    "VICI": "Real Estate",
    "VICR": "Information Technology",
    "VIK": "Consumer Discretionary",
    "VIPS": "Consumer Discretionary",
    "VIRT": "Financials",
    "VISN": "Information Technology",
    "VIST": "Energy",
    "VKTX": "Health Care",
    "VLTO": "Industrials",
    "VLY": "Financials",
    "VMC": "Industrials",
    "VMI": "Industrials",
    "VMRK": "Real Estate",
    "VNET": "Information Technology",
    "VNO": "Real Estate",
    "VNOM": "Energy",
    "VNT": "Industrials",
    "VOD": "Communication Services",
    "VOR": "Health Care",
    "VOYA": "Financials",
    "VOYG": "Industrials",
    "VPG": "Information Technology",
    "VRDN": "Health Care",
    "VRNS": "Information Technology",
    "VRSK": "Information Technology",
    "VRSN": "Information Technology",
    "VRT": "Information Technology",
    "VRTS": "Financials",
    "VSAT": "Consumer Discretionary",
    "VSEC": "Consumer Discretionary",
    "VSH": "Information Technology",
    "VSNT": "Industrials",
    "VSXY": "Consumer Discretionary",
    "VTR": "Real Estate",
    "VTRS": "Health Care",
    "VVV": "Industrials",
    "VVX": "Consumer Discretionary",
    "VYX": "Miscellaneous",
    "WAB": "Industrials",
    "WAFD": "Financials",
    "WAL": "Financials",
    "WAY": "Information Technology",
    "WBI": "Energy",
    "WCC": "Consumer Discretionary",
    "WCN": "Utilities",
    "WDFC": "Industrials",
    "WEC": "Utilities",
    "WEN": "Consumer Discretionary",
    "WERN": "Industrials",
    "WEX": "Consumer Discretionary",
    "WFRD": "Consumer Discretionary",
    "WGS": "Health Care",
    "WH": "Consumer Discretionary",
    "WHD": "Consumer Discretionary",
    "WHR": "Consumer Discretionary",
    "WING": "Consumer Discretionary",
    "WIX": "Information Technology",
    "WK": "Information Technology",
    "WKC": "Energy",
    "WLK": "Industrials",
    "WLY": "Consumer Discretionary",
    "WMG": "Consumer Discretionary",
    "WMS": "Consumer Discretionary",
    "WOLF": "Information Technology",
    "WPC": "Real Estate",
    "WPM": "Materials",
    "WRB": "Financials",
    "WRBY": "Health Care",
    "WSBC": "Financials",
    "WSC": "Industrials",
    "WSFS": "Financials",
    "WSM": "Consumer Discretionary",
    "WSO": "Consumer Discretionary",
    "WST": "Health Care",
    "WT": "Financials",
    "WTFC": "Financials",
    "WTM": "Financials",
    "WTRG": "Utilities",
    "WTS": "Industrials",
    "WTTR": "Energy",
    "WTW": "Financials",
    "WU": "Consumer Discretionary",
    "WULF": "Financials",
    "WWD": "Energy",
    "WY": "Real Estate",
    "WYFI": "Financials",
    "WYNN": "Consumer Discretionary",
    "XENE": "Health Care",
    "XMTR": "Consumer Discretionary",
    "XNCR": "Health Care",
    "XP": "Financials",
    "XPEV": "Industrials",
    "XPO": "Consumer Discretionary",
    "XRAY": "Health Care",
    "XYL": "Industrials",
    "XYZ": "Information Technology",
    "YELP": "Consumer Discretionary",
    "YETI": "Consumer Discretionary",
    "YMM": "Information Technology",
    "YOU": "Information Technology",
    "YPF": "Energy",
    "YSS": "Industrials",
    "YUMC": "Consumer Discretionary",
    "Z": "Consumer Discretionary",
    "ZBH": "Health Care",
    "ZBIO": "Health Care",
    "ZD": "Communication Services",
    "ZETA": "Information Technology",
    "ZG": "Consumer Discretionary",
    "ZIM": "Consumer Discretionary",
    "ZION": "Financials",
    "ZLAB": "Health Care",
    "ZM": "Information Technology",
    "ZTO": "Industrials",
    "ZWS": "Industrials",
}
